version: 2

project_name: archguard

before:
  hooks:
    - go mod tidy

builds:
  - id: archguard
    main: ./cmd/archguard
    binary: archguard
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/honzikec/archguard/internal/cli.Version={{.Version}}
      - -X github.com/honzikec/archguard/internal/cli.Commit={{.Commit}}
      - -X github.com/honzikec/archguard/internal/cli.BuildDate={{.Date}}

archives:
  - id: archguard
    ids:
      - archguard
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums_windows_amd64.txt

release:
  mode: append

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
